#!/usr/bin/env bash
set -euo pipefail

package_root="$1"
output_dir="$2"
output_file="$output_dir/BuildInfo.generated.swift"
repository_root="$package_root/../.."

git_sha="unknown"
if git -C "$repository_root" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git_sha="$(git -C "$repository_root" rev-parse HEAD)"
fi

mkdir -p "$output_dir"
cat > "$output_file" <<EOF
// Generated by BuildInfoPlugin during every alln SwiftPM build. Do not hand-edit.
enum BuildInfo {
    static let gitSha = "$git_sha"
    static let buildTime = "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
}
EOF
