// Build identity for `alln version --json` (ASF-S06).
// Generated by scripts/generate_build_info.sh — do not hand-edit.
// Release / dogfood builds should refresh this before `swift build -c release --product alln`.
enum BuildInfo {
    static let gitSha = "791d591e27cc21f855161dd3a3ca8e8a05b43016"
    static let buildTime = "2026-07-19T23:09:12Z"
}
