// Build identity for `alln version --json` (ASF-S06).
// Generated by scripts/generate_build_info.sh — do not hand-edit.
// Release / dogfood builds should refresh this before `swift build -c release --product alln`.
enum BuildInfo {
    static let gitSha = "3f64a7d6beaa5e3b2a03c0c45b1f74ca202b4a6f"
    static let buildTime = "2026-07-20T22:32:56Z"
}
