#!/usr/bin/env bash
# Allnighter green wall — extend as Swift targets land.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CHECK_STARTED_AT=$SECONDS
# shellcheck source=ensure-test-guard-path.sh disable=SC1091
source "$ROOT/scripts/ensure-test-guard-path.sh"

# TIU-S01: cheap hygiene first (no compile/test suites).
bash "$ROOT/scripts/check-fast.sh"
ran_any=true

# ASF-S06: BuildInfo is generated by BuildInfoPlugin whenever SwiftPM builds
# the `alln` target. There is deliberately no separate pre-build script for an
# agent to remember or for this wall to mutate.

if [[ -f "$ROOT/Packages/AllnighterCore/Package.swift" ]]; then
  echo "==> swift test AllnighterCore"
  ALLNIGHTER_SWIFT_TEST_TIMEOUT_SECONDS="${ALLNIGHTER_SWIFT_TEST_TIMEOUT_SECONDS:-3600}" \
    bash "$ROOT/scripts/swift-test.sh"
  ran_any=true

  # Structural fixture mode (policy + absence checks). Filtered swift tests are
  # skipped here when the full suite already ran above (TIU-S02).
  echo "==> code red structural works test"
  ALLNIGHTER_STRUCTURAL_SKIP_SWIFT_TEST=1 \
    bash "$ROOT/scripts/code_red_works_test.sh" structural
  ran_any=true

  # ASF-S08: contract drift gate (same check StandingInvariants runs opportunistically).
  echo "==> alln dev export-contracts --check"
  ALLN_BIN=""
  if [[ -x "$ROOT/Packages/AllnighterCore/.build/debug/alln" ]]; then
    ALLN_BIN="$ROOT/Packages/AllnighterCore/.build/debug/alln"
  elif [[ -x "$ROOT/Packages/AllnighterCore/.build/release/alln" ]]; then
    ALLN_BIN="$ROOT/Packages/AllnighterCore/.build/release/alln"
  elif command -v alln >/dev/null 2>&1; then
    ALLN_BIN="$(command -v alln)"
  fi
  if [[ -n "$ALLN_BIN" ]]; then
    ( cd "$ROOT" && "$ALLN_BIN" dev export-contracts --check )
  else
    echo "check: no alln binary found after swift test; building product alln for export-contracts --check"
    # build is not gated; only `test` is.
    swift build --package-path "$ROOT/Packages/AllnighterCore" --product alln
    ( cd "$ROOT" && "$ROOT/Packages/AllnighterCore/.build/debug/alln" dev export-contracts --check )
  fi
  ran_any=true
fi

# Mac app (XcodeGen-generated project; regenerate so .xcodeproj need not be committed).
MAC_APP="$ROOT/Apps/AllnighterMac"
if [[ -f "$MAC_APP/project.yml" ]] && command -v xcodegen >/dev/null 2>&1; then
  echo "==> xcodegen generate (AllnighterMac)"
  ( cd "$MAC_APP" && xcodegen generate >/dev/null )
  echo "==> xcodebuild test AllnighterMac"
  # CR-S07: all three Code Red skips are RETIRED — every Mac test is on the wall.
  # The two relay tests were repaired by giving them their own stub driver and
  # workers instead of seating the user's live catalog; see their doc comments.
  #
  # Wall-local DerivedData (not Xcode's default ~/Library/.../DerivedData):
  # Core API renames can leave a stale AllnighterCore.swiftmodule that Engine
  # still imports, producing "missing argument for parameter …" compile errors
  # against sources that SPM already accepts. Isolate the wall from the IDE
  # cache, and wipe only when Core/Engine sources outrun the cached modules
  # (or modules disagree with each other) — warm incremental stays cheap.
  MAC_DD="${ALLNIGHTER_MAC_DERIVED_DATA:-$ROOT/.build/DerivedData-AllnighterMac}"
  CORE_SOURCES="$ROOT/Packages/AllnighterCore/Sources"
  if [[ -d "$MAC_DD" ]]; then
    # Exit 0 = stale/skewed (wipe); exit 1 = warm cache is fine.
    if python3 - "$MAC_DD" "$CORE_SOURCES" <<'PY'
import os, sys
dd, src_root = sys.argv[1], sys.argv[2]
mod_mtimes = []
for root, dirs, files in os.walk(dd):
    # Directory-style .swiftmodule bundles
    for d in dirs:
        if d == "AllnighterCore.swiftmodule" or (
            d.endswith(".swiftmodule") and "AllnighterCore" in d and "AllnighterEngine" not in d
        ):
            path = os.path.join(root, d)
            try:
                mod_mtimes.append(os.path.getmtime(path))
            except OSError:
                pass
    for f in files:
        if not f.endswith(".swiftmodule"):
            continue
        path = os.path.join(root, f)
        # Only AllnighterCore product modules (skip Engine / other packages).
        if "AllnighterCore" not in path or "AllnighterEngine" in path:
            continue
        try:
            mod_mtimes.append(os.path.getmtime(path))
        except OSError:
            pass
if not mod_mtimes:
    sys.exit(1)  # cold cache — nothing to invalidate
src_mtimes = []
for root, _dirs, files in os.walk(src_root):
    for f in files:
        if f.endswith(".swift"):
            try:
                src_mtimes.append(os.path.getmtime(os.path.join(root, f)))
            except OSError:
                pass
# Sources newer than the oldest cached Core module → wipe.
if src_mtimes and max(src_mtimes) > min(mod_mtimes):
    sys.exit(0)
# Dual-location module skew (e.g. Products/ vs PackageFrameworks/) → wipe.
if max(mod_mtimes) - min(mod_mtimes) > 1.0:
    sys.exit(0)
sys.exit(1)
PY
    then
      echo "check: stale/skewed AllnighterCore modules vs Packages/AllnighterCore/Sources; cleaning $MAC_DD"
      rm -rf "$MAC_DD"
    fi
  fi
  mkdir -p "$MAC_DD"

  # Signing for the Mac wall:
  # CODE_SIGNING_ALLOWED=NO shipped with Phase 03 (557eac95) so agents/CI without a
  # developer identity could still *build*. On modern macOS it leaves the XCTest
  # host unsigned; the runner then hangs ~5+ minutes ("test runner hung before
  # establishing connection") and executes ZERO tests — a wall that burns time and
  # trains people to ignore failures. Never reintroduce that flag.
  #
  # Prefer project signing (Automatic + DEVELOPMENT_TEAM in project.yml) when a
  # codesigning identity is present. With no identity, ad-hoc sign the host so the
  # runner can still load it (signed, just not team-signed).
  xcode_signing_args=()
  if security find-identity -v -p codesigning 2>/dev/null \
    | grep -Eq 'Apple Development|Mac Developer|Developer ID Application|Apple Distribution'; then
    echo "check: codesigning identity present — using project signing (no CODE_SIGNING_ALLOWED=NO)"
  else
    echo "check: no codesigning identity in keychain — ad-hoc signing Mac test host"
    xcode_signing_args+=(
      CODE_SIGN_IDENTITY=-
      CODE_SIGNING_REQUIRED=YES
      CODE_SIGNING_ALLOWED=YES
      DEVELOPMENT_TEAM=
      CODE_SIGN_STYLE=Manual
    )
  fi

  export ALLNIGHTER_TEST_TOKEN
  ALLNIGHTER_TEST_TOKEN="$(python3 "$ROOT/scripts/allnighter_test_token.py" mint "$ROOT")"
  xcode_log="$(mktemp "${TMPDIR:-/tmp}/alln-xcodebuild-test.XXXXXX")"
  xcode_status=0
  mac_phase_started=$SECONDS
  # Keep the last few progress lines on the console; full log is teed for diagnostics.
  # bash 3.2 + set -u: empty `"${arr[@]}"` is unbound (identity-present path
  # leaves xcode_signing_args empty). Use the same form as agent_eval.sh.
  xcodebuild test \
    -project "$MAC_APP/AllnighterMac.xcodeproj" \
    -scheme AllnighterMac \
    -destination 'platform=macOS' \
    -derivedDataPath "$MAC_DD" \
    ${xcode_signing_args[@]+"${xcode_signing_args[@]}"} \
    2>&1 | tee "$xcode_log" | tail -3 || xcode_status=${PIPESTATUS[0]}
  mac_phase_elapsed=$((SECONDS - mac_phase_started))

  # xcodebuild sometimes exits 0 even when the suite reports failures.
  if [[ "$xcode_status" -eq 0 ]] && rg -q 'TEST FAILED|with [1-9][0-9]* failures?' "$xcode_log" 2>/dev/null; then
    xcode_status=1
  fi

  # Count executed test cases from XCTest summary lines ("Executed N tests, …").
  # Prefer the largest N (outer "All tests" suite) so nested suite lines do not
  # under-count; missing summary → 0 (instrument fault below).
  mac_tests_executed="$(
    python3 - "$xcode_log" <<'PY'
import re, sys
path = sys.argv[1]
best = 0
try:
    text = open(path, errors="replace").read()
except OSError:
    print(0)
    raise SystemExit
for m in re.finditer(r"Executed\s+(\d+)\s+tests?", text):
    n = int(m.group(1))
    if n > best:
        best = n
print(best)
PY
  )"

  instrument_fault=0
  instrument_reason=""
  if rg -q 'test runner hung|hung before establishing connection' "$xcode_log" 2>/dev/null; then
    instrument_fault=1
    instrument_reason="Mac test runner hung before establishing connection (zero tests executed)"
  elif [[ "${mac_tests_executed:-0}" -eq 0 ]]; then
    # Build may have succeeded and xcodebuild may even have exited 0 — still a
    # wall instrument fault. A green wall that ran nothing is banned.
    instrument_fault=1
    instrument_reason="Mac suite executed ZERO test cases (not a pass, not an ordinary failure)"
  fi

  if [[ "$instrument_fault" -eq 1 ]]; then
    xcode_status=1
    echo "check: INSTRUMENT FAULT — ${instrument_reason}"
    echo "check: Mac phase elapsed ${mac_phase_elapsed}s; executed=${mac_tests_executed:-0}"
    echo "check: this is not a product test failure — the wall could not run the suite."
  elif [[ "$xcode_status" -eq 0 ]]; then
    echo "check: Mac suite executed ${mac_tests_executed} tests in ${mac_phase_elapsed}s"
  fi

  if [[ "$xcode_status" -ne 0 ]]; then
    if [[ "$instrument_fault" -eq 0 ]]; then
      echo "check: xcodebuild failed (exit $xcode_status). Diagnostics:"
    else
      echo "check: xcodebuild instrument fault (exit $xcode_status). Diagnostics:"
    fi
    # Surface hang/zero-run, compile errors, and failing assertions — not just "(N failures)".
    if command -v rg >/dev/null 2>&1; then
      rg -n --no-heading \
        'test runner hung|hung before establishing connection|Executed 0 tests|error: |fatal error: |\.swift:[0-9]+:[0-9]+: error:|TEST FAILED|Testing failed|with [1-9][0-9]* failures?|XCTAssert|failed \(|error: -\[|\*\* TEST BUILD FAILED \*\*|\*\* TEST FAILED \*\*|\*\* BUILD FAILED \*\*|INSTRUMENT FAULT' \
        "$xcode_log" | head -100 || true
    else
      grep -nE 'test runner hung|Executed 0 tests|error: |TEST FAILED|XCTAssert|BUILD FAILED' "$xcode_log" | head -100 || true
    fi
    echo "check: full xcodebuild log preserved at: $xcode_log"
    # Do not delete the log on failure — evidence is the product.
  else
    rm -f "$xcode_log"
  fi
  python3 "$ROOT/scripts/allnighter_test_token.py" burn "$ROOT" "$ALLNIGHTER_TEST_TOKEN" 2>/dev/null || true
  unset ALLNIGHTER_TEST_TOKEN
  [[ "$xcode_status" -eq 0 ]] || exit "$xcode_status"
  ran_any=true
elif [[ -f "$MAC_APP/project.yml" ]]; then
  echo "check: xcodegen not installed; skipping Mac app (run: brew install xcodegen)"
fi

if [[ "$ran_any" == false ]]; then
  echo "check: no Swift targets yet (docs-only bootstrap OK)"
fi

elapsed=$((SECONDS - CHECK_STARTED_AT))
# Integer tenths avoid nested-quote awk: `"$(awk "BEGIN {… \"%.1f\", …}")"` toggles
# quotes so bash brace-expands `{printf…, expr}` into two failed awks; printf then
# reuses the format and prints the footer twice (real Ns + spurious 0s / 0.0m).
mins_tenths=$((elapsed * 10 / 60))
printf 'check: done in %ds (%d.%dm wall)\n' "$elapsed" "$((mins_tenths / 10))" "$((mins_tenths % 10))"
