#!/usr/bin/env bash
# Allnighter green wall — extend as Swift targets land.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

ran_any=false

# TIU-S01: cheap hygiene first (no compile/test suites).
bash "$ROOT/scripts/check-fast.sh"
ran_any=true

# ASF-S06: BuildInfo is generated by BuildInfoPlugin whenever SwiftPM builds
# the `alln` target. There is deliberately no separate pre-build script for an
# agent to remember or for this wall to mutate.

if [[ -f "$ROOT/Packages/AllnighterCore/Package.swift" ]]; then
  echo "==> swift test AllnighterCore"
  ALLNIGHTER_SWIFT_TEST_TIMEOUT_SECONDS="${ALLNIGHTER_SWIFT_TEST_TIMEOUT_SECONDS:-3600}" \
    bash "$ROOT/scripts/swift-test.sh"
  ran_any=true

  # Structural fixture mode (policy + absence checks). Filtered swift tests are
  # skipped here when the full suite already ran above (TIU-S02).
  echo "==> code red structural works test"
  ALLNIGHTER_STRUCTURAL_SKIP_SWIFT_TEST=1 \
    bash "$ROOT/scripts/code_red_works_test.sh" structural
  ran_any=true

  # ASF-S08: contract drift gate (same check StandingInvariants runs opportunistically).
  echo "==> alln dev export-contracts --check"
  ALLN_BIN=""
  if [[ -x "$ROOT/Packages/AllnighterCore/.build/debug/alln" ]]; then
    ALLN_BIN="$ROOT/Packages/AllnighterCore/.build/debug/alln"
  elif [[ -x "$ROOT/Packages/AllnighterCore/.build/release/alln" ]]; then
    ALLN_BIN="$ROOT/Packages/AllnighterCore/.build/release/alln"
  elif command -v alln >/dev/null 2>&1; then
    ALLN_BIN="$(command -v alln)"
  fi
  if [[ -n "$ALLN_BIN" ]]; then
    ( cd "$ROOT" && "$ALLN_BIN" dev export-contracts --check )
  else
    echo "check: no alln binary found after swift test; building product alln for export-contracts --check"
    # build is not gated; only `test` is.
    swift build --package-path "$ROOT/Packages/AllnighterCore" --product alln
    ( cd "$ROOT" && "$ROOT/Packages/AllnighterCore/.build/debug/alln" dev export-contracts --check )
  fi
  ran_any=true
fi

# Mac app (XcodeGen-generated project; regenerate so .xcodeproj need not be committed).
MAC_APP="$ROOT/Apps/AllnighterMac"
if [[ -f "$MAC_APP/project.yml" ]] && command -v xcodegen >/dev/null 2>&1; then
  echo "==> xcodegen generate (AllnighterMac)"
  ( cd "$MAC_APP" && xcodegen generate >/dev/null )
  echo "==> xcodebuild test AllnighterMac"
  # CR-S07: all three Code Red skips are RETIRED — every Mac test is on the wall.
  # The two relay tests were repaired by giving them their own stub driver and
  # workers instead of seating the user's live catalog; see their doc comments.
  export ALLNIGHTER_TEST_TOKEN
  ALLNIGHTER_TEST_TOKEN="$(python3 "$ROOT/scripts/allnighter_test_token.py" mint "$ROOT")"
  xcode_status=0
  xcodebuild test \
    -project "$MAC_APP/AllnighterMac.xcodeproj" \
    -scheme AllnighterMac \
    -destination 'platform=macOS' \
    CODE_SIGNING_ALLOWED=NO | tail -3 || xcode_status=$?
  python3 "$ROOT/scripts/allnighter_test_token.py" burn "$ROOT" "$ALLNIGHTER_TEST_TOKEN" 2>/dev/null || true
  unset ALLNIGHTER_TEST_TOKEN
  [[ "$xcode_status" -eq 0 ]] || exit "$xcode_status"
  ran_any=true
elif [[ -f "$MAC_APP/project.yml" ]]; then
  echo "check: xcodegen not installed; skipping Mac app (run: brew install xcodegen)"
fi

if [[ "$ran_any" == false ]]; then
  echo "check: no Swift targets yet (docs-only bootstrap OK)"
fi
