#!/usr/bin/env bash
# Embed git SHA + UTC build timestamp into AllnighterCLI/BuildInfo.swift (ASF-S06).
# Safe to run outside a git checkout (falls back to "unknown").
# Release builds should run this before `swift build -c release --product alln`.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/Packages/AllnighterCore/Sources/AllnighterCLI/BuildInfo.swift"

git_sha="unknown"
if git -C "$ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git_sha="$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
fi
build_time="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

# Escape for a Swift string literal (SHA/time are hex/ISO today; keep this defensive).
swift_escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

cat > "$OUT" <<EOF
// Build identity for \`alln version --json\` (ASF-S06).
// Generated by scripts/generate_build_info.sh — do not hand-edit.
// Release / dogfood builds should refresh this before \`swift build -c release --product alln\`.
enum BuildInfo {
    static let gitSha = "$(swift_escape "$git_sha")"
    static let buildTime = "$(swift_escape "$build_time")"
}
EOF

echo "generate_build_info: wrote gitSha=${git_sha:0:12}… buildTime=$build_time → $OUT"
